### ISSUE TITLE
ESPAsyncUSP::stopAll() request

### ISSUE THREAD

**Issue by Stephan35** [me-no-dev/ESPAsyncUDP#10]
Hello,
It is not an issue , but a request .
Because my WiFi.localIP() may change, i need to launch a new listener udp event.
I don't really know if i have to stop actual listener before launching another one on another IP
Thanks for help.
Best regards.

**Comment by me-no-dev** [comment]
what kind of server? you should not need to do anything at all if the server is listening on all interfaces.

**Comment by Stephan35** [comment]
```C++
if(udp.listen(localUdpPort)) {
    Serial.print("*** UDP Listening on IP: ");
    Serial.println(WiFi.localIP());
```

> *** UDP Listening on IP:  IP 10.0.1.101, UDP port 4210

so, if you mean that udp.listen(port) can listen all interfaces, that is ok for me .
So i don't have to kill current listening process ?

**Comment by me-no-dev** [comment]
exactly ;) no need to restart the server when IP is changed or network is connected/disconnected

**Comment by Stephan35** [comment]
Thanks for your reply.
You can close ;-)
