### ISSUE TITLE
AsyncUDP.cpp:248:57: error: 'udp_set_multicast_netif_addr' was not declared in this scope

### ISSUE THREAD

**Issue by rolfberkenbosch** [me-no-dev/ESPAsyncUDP#17]
I get the following error in Arduino IDE:

Arduino: 1.8.5 (Windows 10), Board: "WeMos D1 R2 & mini, 160 MHz, 115200, 4M (3M SPIFFS)"

C:\Program Files (x86)\Arduino\libraries\ESPAsyncUDP-master\src\AsyncUDP.cpp: In member function 'bool AsyncUDP::listenMulticast(ip_addr_t*, uint16_t, uint8_t)':

C:\Program Files (x86)\Arduino\libraries\ESPAsyncUDP-master\src\AsyncUDP.cpp:248:57: error: 'udp_set_multicast_netif_addr' was not declared in this scope

     udp_set_multicast_netif_addr(_pcb, multicast_if_addr);

                                                         ^

C:\Program Files (x86)\Arduino\libraries\ESPAsyncUDP-master\src\AsyncUDP.cpp:249:36: error: 'udp_set_multicast_ttl' was not declared in this scope

     udp_set_multicast_ttl(_pcb, ttl);

                                    ^

exit status 1
Error compiling for board WeMos D1 R2 & mini.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by me-no-dev** [comment]
Old esp8266 arduino :)
