### ISSUE TITLE
ESP8266 Module error

### ISSUE THREAD

**Issue by ukpaulthm** [me-no-dev/ESPAsyncUDP#22]
hi all
I keep getting this error could anyone tell me why this is please?

Arduino: 1.8.5 (Windows 8), Board: "Generic ESP8266 Module, 80 MHz, ck, 26 MHz, 40MHz, DOUT, 1M (64K SPIFFS), v2 Prebuilt (MSS=536), Disabled, None, 115200"

C:\Users\c\Desktop\New folder (17)\Sonoff-Tasmota-5.10.0\sonoff\xdrv_irremote.ino:25:29: fatal error: IRremoteESP8266.h: No such file or directory

 #include <IRremoteESP8266.h>

                             ^

compilation terminated.

exit status 1
Error compiling for board Generic ESP8266 Module.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by TheCallOfTheWild** [comment]
bro just download IRremoteESP8266 library from here: https://github.com/markszabo/IRremoteESP8266
press clone or download (green color) and download zip.
Now in arduino app press scratch . Then include library and then incude zip and then include the zip file downloaded from github(u may find it at downloads).Hope that helped :)

**Comment by ascillato** [comment]
see #25
