### ISSUE TITLE
ESP32 version

### ISSUE THREAD

**Issue by gmag11** [me-no-dev/ESPAsyncUDP#24]
Thank you for such a nice library. Is there any plan to release any ESP32 compatible version?

**Comment by JanVelleman** [comment]
Curious too

**Comment by ristomatti** [comment]
@gmag11 @JanVelleman Unless you've already found out, It seems to be part of esp32 core: https://github.com/espressif/arduino-esp32/tree/master/libraries/AsyncUDP

**Comment by gmag11** [comment]
Yes. Just this week I found that, at least, last version of esp32 Arduino core has this library included. Thank you very much.
