### ISSUE TITLE
Error compiling for board NodeMCU 0.9 (ESP-12 Module)

### ISSUE THREAD

**Issue by TheCallOfTheWild** [me-no-dev/ESPAsyncUDP#28]
Can u help me please?

In file included from C:\Users\pc\Desktop\jammer\esp8266_deauther-master\esp8266_deauther\esp8266_deauther.ino:13:0:

sketch\functions.h:9:25: fatal error: ArduinoJson.h: No such file or directory

 #include "ArduinoJson.h"

                         ^

compilation terminated.

exit status 1
Error compiling for board NodeMCU 0.9 (ESP-12 Module).

#I have tried  NodeMCU 1.0(ESP-12E Module) and Generic ESP8266 Module too but it gives me the same error

**Comment by ore2srs56** [comment]
how to fix it ?
