### ISSUE TITLE
AsyncUDPMulticastServer.ino example

### ISSUE THREAD

**Issue by MolsonB** [me-no-dev/ESPAsyncUDP#8]
In your example AsyncUDPMulticastServer.ino, in the loop function, should it read  udp.broadcast instead of udp.print ?

**Comment by me-no-dev** [comment]
there are 3 types of transmission: unicast, multicast and broadcast. broadcasting is when you send to all members of your subnet, multicasting is when you send to a special multicast IP and port and anyone on the same LAN can also listen to that address and port and can get the packet (mDNS, SSDP and many more services work like that). The third type is the most usual one: you send to a particular IP and port and the other end is also listening on the given port.

Now back on your question: You are talking about multicast server and that is not broadcast (though you can also broadcast with the multicast server), so printing to the multicast server means that the server will send the packet to the multicast address and not the broadcast one :)

BTW, really sorry I missed your question.... I have no idea how that happened
